# prettier config file

printWidth = 80
tabWidth = 2
useTabs = true
semi = true
singleQuote = false
quoteProps = "consistent"
jsxSingleQuote = false
trailingComma = "all"
bracketSpacing = true
bracketSameLine = true
arrowParens = "avoid"
insertPragma = true
proseWrap = "preserve"
htmlWhitespaceSensitivity = "css"
vueIndentScriptAndStyle = true
endOfLine = "lf"
embeddedLanguageFormatting = "auto"